//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodTruck
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commande_Article
    {
        public int CommandeId { get; set; }
        public int ArticleId { get; set; }
        public int Quantite { get; set; }
        public double PrixTotalHT { get; set; }
        public double PrixTotalTTC { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Commande Commande { get; set; }
    }
}
