//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodTruck
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commande
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Commande()
        {
            this.Commande_Article = new HashSet<Commande_Article>();
            this.Facture = new HashSet<Facture>();
        }
    
        public int Id { get; set; }
        public int ClientId { get; set; }
        public System.DateTime DateCommande { get; set; }
        public System.DateTime DateRetrait { get; set; }
        public double RemiseFidelite { get; set; }
        public double RemiseCommerciale { get; set; }
        public bool Retrait { get; set; }
        public bool Annulation { get; set; }
        public double PrixTotalHT { get; set; }
        public double PrixTotalTTC { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Commande_Article> Commande_Article { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facture> Facture { get; set; }
    }
}
