//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodTruck.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class foodtruckEntities : DbContext
    {
        public foodtruckEntities()
            : base("name=foodtruckEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Article> Article { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<CodePromo> CodePromo { get; set; }
        public virtual DbSet<Commande> Commande { get; set; }
        public virtual DbSet<Commande_Article> Commande_Article { get; set; }
        public virtual DbSet<CreerAdmin> CreerAdmin { get; set; }
        public virtual DbSet<FamilleArticle> FamilleArticle { get; set; }
        public virtual DbSet<JourExceptionnel> JourExceptionnel { get; set; }
        public virtual DbSet<OubliMotDePasse> OubliMotDePasse { get; set; }
        public virtual DbSet<OuvertureHebdomadaire> OuvertureHebdomadaire { get; set; }
        public virtual DbSet<Panier> Panier { get; set; }
        public virtual DbSet<PanierProspect> PanierProspect { get; set; }
        public virtual DbSet<Visite> Visite { get; set; }
        public virtual DbSet<Facture> Facture { get; set; }
        public virtual DbSet<Tva> Tva { get; set; }
    }
}
