//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodTruck
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visite
    {
        public int Id { get; set; }
        public string AdresseIp { get; set; }
        public System.DateTime Date { get; set; }
        public string Url { get; set; }
        public int ClientId { get; set; }
        public string Navigateur { get; set; }
        public bool NavigateurMobile { get; set; }
        public string UrlOrigine { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
